version: "3.3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER= user
      - POSTGRES_PASSWORD= password
      - POSTGRES_DB= pedidos_db
    ports:
      - "5432:5432"